DJ1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.static import serve 
from rest_framework_simplejwt import views as jwt_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('', include('base.urls')),
    path('', include('myapp.urls')),
    path('', include('moto.urls')),
    path('',include('caisseTana.urls')),
    path('',include('caisseTamatave.urls')),
    path('',include('versement.urls')),
    path('',include('importateur.urls')),
    path('',include('exportateur.urls')),
    path('',include('compagnie.urls')),
    path('',include('operation.urls')),
    path('',include('facture.urls')),
    path('accounts/', include('allauth.urls')),
    path('',include('accounts.urls')),
    path('',include('commercial.urls')),
    path('',include('caisseMoto.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    import mimetypes
    mimetypes.add_type("application/javascript",".js",True)

facture/urls.py
from django.urls import path
from facture import views
urlpatterns = [
    path('facture/edit/<int:id>',views.editFacture,name='editFacture'),
    path('facture/preview/<int:id>',views.previewFacture,name='previewFacture'),
    path('facture/initFacture',views.initFacture,name='initFacture'),
    path('facture/editFactureMoto/<int:id>',views.editFactureMoto,name='editFactureMoto'),
    path('facture/editBLMoto/<int:id>',views.editBLMoto,name='editBLMoto'),
    path('facture/previewFactureMoto/<int:id>',views.previewFactureMoto,name='previewFactureMoto'),
    path('facture/previewBLMoto/<int:id>',views.previewBLMoto,name='previewBLMoto'),
    path('facture/total2word/<int:number>',views.total2word,name='total2word'),
]

moto/models.py
from django.db import models

# Create your models here.
class Moto(models.Model):
    ID_Moto = models.IntegerField(blank=True,null=True,unique=True)
    date_entree = models.DateField(auto_now=False,blank=True,null=True)
    nom_moto = models.CharField(max_length=50,blank=True,null=True)
    num_moteur = models.CharField(max_length=50,blank=True,null=True,unique=True)
    FRN = models.CharField(max_length=50,blank=True,null=True)
    PA = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    PV = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    date_vente = models.DateField(auto_now=False,null=True,blank=True)
    nom_client_1 = models.CharField(max_length=50, blank=True,null=True)
    CIN_Num_Client_1 = models.CharField(max_length=50, blank=True,null=True)
    PJ_CIN_Client_1_recto = models.ImageField(blank=True,null=True,upload_to='images')
    PJ_CIN_Client_1_verso = models.ImageField(blank=True,null=True,upload_to='images')
    tel_client_1 = models.CharField(max_length=50, blank=True,null=True)
    adresse_client_1 = models.CharField(max_length=50, blank=True,null=True)
    num_BL = models.IntegerField(null=True,unique=True)
    num_sur_facture = models.IntegerField(null=True,unique=True)
    PJ_Facture = models.FileField(blank=True, null=True, upload_to='images')
    nom_client_2 = models.CharField(max_length=50, blank=True,null=True)
    tel_client_2 = models.CharField(max_length=50, blank=True,null=True)
    adresse_client_2 = models.CharField(max_length=50, blank=True,null=True)
    CIN_Num_Client_2 = models.CharField(max_length=50, blank=True,null=True)
    PJ_CIN_Client_2_recto = models.ImageField(blank=True,null=True,upload_to='images')
    PJ_CIN_Client_2_verso = models.ImageField(blank=True,null=True,upload_to='images')
    montant_reparation = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    motif_reparation = models.CharField(max_length=50,blank=True,null=True)
    commercial = models.CharField(max_length=50,blank=True,null=True)
    volume_moteur = models.CharField(max_length=50,blank=True,null=True)
    PU_HT = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    TVA = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    PT = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    montant_lettre = models.CharField(max_length=50,blank=True)
    Ref = models.IntegerField(blank=True, null=True)
    archive = models.BooleanField(default=False)
    carte_rose = models.CharField(max_length=50,blank=True,null=True)
    carte_grise = models.CharField(max_length=50,blank=True,null=True)
    model_no_1 = models.CharField(max_length=50,blank=True,null=True)
    magasin = models.CharField(max_length=50,blank=True,null=True)
    date_facture = models.DateField(auto_now = False, null = True,blank=True)
    date_BL = models.DateField(auto_now = False, null = True)
    localisation = models.CharField(max_length=50,blank=True,null=True)
    date_arrivee = models.DateField(auto_now = False, null = True)
    fournisseur = models.CharField(max_length=50,blank=True,null=True)
    
    def __str__(self):
        return self.nom_moto

facture/forms.py
from django import forms
from django.forms import ModelForm
from operation.models import Operation
from django.core.exceptions import ValidationError
from decimal import Decimal, DecimalException
from django.utils import formats
from django.utils.encoding import force_text
from moto.models import Moto
from .models import FactureMoto

class Thousands(forms.DecimalField):
    def to_python(self, value):
        if value in self.empty_values:
            return None
        if self.localize:
            value = formats.sanitize_separators(value)
        value = force_text(value).strip().replace(' ', '')

        try:
            value = Decimal(value)
        except DecimalException:
            raise ValidationError(
                self.error_messages['invalid'], code='invalid')
        return value

class factureForm(ModelForm):
    Facture_Date_Facture = forms.DateField(widget=forms.DateInput(attrs={'type':'date','class':'form-control w3-margin-bottom','max': 'today'}),required=False)

    Facture_OT_Honoraire = Thousands(label='OT - Honoraire',max_digits=20, decimal_places=2, widget=forms.TextInput())

    Facture_Autres_Montant = Thousands(label='Autres montant',max_digits=20, decimal_places=2, widget=forms.TextInput())

    Facture_BAD_Montant = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Overstay_Montant = Thousands(label='Overstay',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Surestaries_Montant = Thousands(label='Surestaries',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Debarquement = Thousands(label='Debarquement',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Magasinage_Montant = Thousands(label='Magasinage',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Droit_Compromis = Thousands(label='Droit compromis',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Amende_Montant = Thousands(label='Amende',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_OV_Montant = Thousands(label='OV',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_OV_Docker = Thousands(label='Docker',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Montant_Fret = Thousands(label='Fret',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Immobilisation = Thousands(label='Immobilisation',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_SousTotal = Thousands(max_digits=20,decimal_places=2, widget=forms.TextInput())

    TotalFacture = Thousands(max_digits=20,decimal_places=2, widget=forms.TextInput())
    Tax = Thousands(max_digits=20,decimal_places=2, widget=forms.TextInput())


    def __init__(self, *args, **kwargs):
        super(factureForm, self).__init__(*args, **kwargs)

        for name in self.fields.keys():
            if name != 'Facture_Date_Facture':
                self.fields[name].widget.attrs.update({'class': 'form-control'})
                self.fields[name].required = False

    class Meta:
        model = Operation
        fields = [
            'Facture_OT_Honoraire','Facture_Autres_Montant','Facture_BAD_Montant','Facture_Overstay_Montant','Facture_Surestaries_Montant','Facture_Debarquement','Facture_Magasinage_Montant','Facture_Droit_Compromis','Facture_Amende_Montant','Facture_OV_Montant','Facture_OV_Docker','Facture_Montant_Fret','Facture_Immobilisation','Facture_Num_Facture','Facture_Nom_Client','Facture_Adresse_Client','Facture_Contact_Client','Facture_email_client','Facture_Date_Facture','Facture_SousTotal','Tax','TotalFacture'
        ]


class factureMotoForm(ModelForm):
    """docstring for factureMoto."""
    PU_HT = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    TVA = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    PV = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    date_vente = forms.DateField(widget=forms.DateInput(attrs={'type':'date','class':'form-control w3-margin-bottom','max': 'today'}),required=False)
    num_sur_facture = forms.CharField(label="Num facture",widget=forms.TextInput())
    def __init__(self, *args, **kwargs):
        super(factureMotoForm, self).__init__(*args, **kwargs)

        for name in self.fields.keys():
            if name != 'Facture_Date_Facture':
                self.fields[name].widget.attrs.update({'class': 'form-control'})
                self.fields[name].required = False

    class Meta:
        model = Moto
        fields = [
        'nom_client_2','CIN_Num_Client_2','adresse_client_2','tel_client_2','volume_moteur','PU_HT','TVA','PT','montant_lettre','PV','date_vente','Ref','num_sur_facture'
        ]

class BLMotoForm(ModelForm):
    """docstring for factureMoto."""
    PV = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    date_vente = forms.DateField(widget=forms.DateInput(attrs={'type':'date','class':'form-control w3-margin-bottom','max': 'today'}),required=False)
    num_BL= forms.CharField(label="Num BL",widget=forms.TextInput())

    def __init__(self, *args, **kwargs):
        super(BLMotoForm, self).__init__(*args, **kwargs)

        for name in self.fields.keys():
            if name != 'Facture_Date_Facture':
                self.fields[name].widget.attrs.update({'class': 'form-control'})
                self.fields[name].required = False

    class Meta:
        model = Moto
        fields = [
        'nom_client_1','tel_client_1','PU_HT','TVA','PT','PV','date_vente','Ref','num_BL'
        ]

facture/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib import messages

from operation.models import Operation
from .forms import factureForm, factureMotoForm, BLMotoForm
from operation.receptionForm import ReceptionForm
from moto.models import Moto
from facture.models import FactureMoto, BLMoto

from num2words import num2words


# Create your views here.

def editFacture(request, id=None, pk=None):
    operation = get_object_or_404(Operation, pk=id)
    if request.method == 'POST':
        form = factureForm(request.POST, instance=operation)
        if form.is_valid():
            form.save()
            messages.success(request, "success")
        else:
            messages.error(request, "error")
    else:
        form = factureForm(instance=operation)
        recform = ReceptionForm(instance=operation)
        messages.success(request, "success")
    context = {
        'form': form,
        'id': operation.id,
        'pk': id
    }
    return render(request, 'facture/edit.html', context)


def previewFacture(request, id=None):
    Facture = get_object_or_404(Operation, pk=id)
    return render(request, 'facture/preview.html',
                  {'Facture': Facture, 'id': Facture.id, 'client': Facture.Facture_Nom_Client})


def initFacture(request):
    if request.is_ajax and request.method == 'GET':
        id = request.GET.get("id", None)
        print("id = ", id)
        curOp = Operation.objects.get(pk=id)
        Facture_OT_Honoraire = curOp.OT_Honoraire
        print("Facture_OT_Honoraire = ", Facture_OT_Honoraire)
        Facture_Autres_Montant = curOp.Autres_Montant
        Facture_BAD_Montant = curOp.BAD_Montant
        Facture_Overstay_Montant = curOp.Overstay_Montant
        Facture_Surestaries_Montant = curOp.Surestaries_Montant
        Facture_Debarquement = curOp.Montant_MICTSL
        Facture_Magasinage_Montant = curOp.Magasinage_Montant
        Facture_Droit_Compromis = curOp.Droit_Compromis
        Facture_Amende_Montant = curOp.Amende_Montant
        Facture_OV_Montant = curOp.OV_Montant
        Facture_OV_Docker = curOp.OV_Docker
        Facture_Montant_Fret = curOp.Montant_Fret
        Facture_Immobilisation = curOp.Immobilisation
        Facture_Nom_Client = curOp.Client

        return JsonResponse(
            {'Facture_OT_Honoraire': Facture_OT_Honoraire, 'Facture_Autres_Montant': Facture_Autres_Montant,
             'Facture_BAD_Montant': Facture_BAD_Montant, 'Facture_Overstay_Montant': Facture_Overstay_Montant,
             'Facture_Surestaries_Montant': Facture_Surestaries_Montant, 'Facture_Debarquement': Facture_Debarquement,
             'Facture_Magasinage_Montant': Facture_Magasinage_Montant,
             'Facture_Droit_Compromis': Facture_Droit_Compromis, 'Facture_Amende_Montant': Facture_Amende_Montant,
             'Facture_OV_Montant': Facture_OV_Montant, 'Facture_OV_Docker': Facture_OV_Docker,
             'Facture_Montant_Fret': Facture_Montant_Fret, 'Facture_Immobilisation': Facture_Immobilisation,
             'Facture_Nom_Client': Facture_Nom_Client}, status=200)


def editFactureMoto(request, id=None):
    moto = get_object_or_404(Moto, pk=id)
    pageTitle = "Moto n°" + str(id)

    if request.method == 'POST':
        form = factureMotoForm(request.POST, instance=moto)
        if form.is_valid():
            form.save()
            messages.success(request, "success")
        else:
            messages.error(request, 'error')
    else:
        form = factureMotoForm(instance=moto)
    context = {'form': form,
               'moto': moto,
               'pageTitle': pageTitle,
               'pk': id
               }
    return render(request, 'facture/editFacture/editFactureMoto.html', context)


def editBLMoto(request, id=None):
    moto = get_object_or_404(Moto, pk=id)
    numBLlast = BLMoto.objects.last()
    pageTitle = "Moto n°" + str(id)
    if request.method == 'POST':
        form = BLMotoForm(request.POST, instance=moto)
        if form.is_valid():
            form.save()
            messages.success(request, 'success')
        else:
            messages.error(request, 'error')
    else:
        form = BLMotoForm(instance=moto)
    context = {'form': form,
               'moto': moto,
               'pageTitle': pageTitle,
               'pk': id
               }
    return render(request, 'facture/editBL/editBLMoto.html', context)


def previewFactureMoto(request, id=None):
    Facture = get_object_or_404(Moto, pk=id)
    pageTitle = "Moto n°" + str(Facture.ID_Moto)
    context = {
        'Facture': Facture, 
        'pageTitle': pageTitle,
        'pk': id
    }
    return render(request, 'facture/previewFacture/previewFactureMoto.html',context)


def previewBLMoto(request, id=None):
    Facture = get_object_or_404(Moto, pk=id)
    pageTitle = "Moto n°" + str(Facture.ID_Moto)
    context = {
        'Facture': Facture, 
        'pageTitle': pageTitle,
        'pk': id
    }
    return render(request, 'facture/previewBL/previewBLMoto.html', context)

def total2word(request,number):
    word = num2words(number,lang='fr')
    word = word.replace("-"," ")
    return JsonResponse({'Total':word},safe=False)

facture/templates/facture/previewBL/btnRedirPrev.html
<div class="form-inline">
  <a href="{% url 'index' %}" class="btn btn-secondary w3-margin"><i class="fas fa-chevron-left fa-fw"></i>Retour</a>
  <a href="{% url 'editBLMoto' id=pk %}" class="btn btn-warning w3-margin"><i class="fas fa-edit fa-fw"></i>Editer</a>
  <select name="layout" id="layout" class="form-control w3-margin w3-padding">
    <option value="1">Une page par feuille</option>
    <option value="2" selected>Deux pages par feuille</option>
  </select>
  <button class="btn btn-success w3-margin" onclick="ExportPdf()"><i class="fa fa-file-pdf fa-fw"></i> Export PDF</button>
</div>

facture/templates/facture/previewBL/previewBLMoto.html
{% extends 'base/blankbone.html' %}
{% block sidebar %}
{% include 'base/sidebar.html' %}
{% endblock sidebar %}
{% block topbar %}
    {% include "base/topbar2.html" %}
{% endblock topbar %}
{% load static %}
{% block content %}
{% include "facture/previewBL/previewBLMotoWredir.html" %}
{% endblock content %}
{% block js %}
<script type="text/javascript">
  $(document).ready(function(){
    $('#pageTitle').addClass('fas fa-motorcycle fa-fw w3-margin-right');
    $('#motoMenu').addClass("active");
    let val = $('#layout').val()
    console.log(val)
    if (val === "1"){
      $('#myCanvasDouble').hide();
      $('#myCanvas').show();
    }
    else if (val === "2"){
      $('#myCanvas').hide();
      $('#myCanvasDouble').show();
    }
  })

  $("#layout").change(function(){
    let val = $('#layout').val()
    console.log(val)
    if (val === "1"){
      $('#myCanvasDouble').hide();
      $('#myCanvas').show();
    }
    else if (val === "2"){
      $('#myCanvas').hide();
      $('#myCanvasDouble').show();
    }
  })
</script>
<script src="{% static 'facture/js/html2pdf.bundle.min.js' %}" charset="utf-8"></script>
<script src="{% static 'facture/js/script.js' %}" charset="utf-8"></script>

{% endblock js %}

facture/templates/facture/previewBL/previewBLMotoTemplate.html
{% load l10n %}
{% load static %}
<link rel="stylesheet" href="{% static 'facture/css/kendo.common-material.min.css' %}">
<link rel="stylesheet" href="{% static 'facture/css/kendo.material.min.css' %}">
<link rel="stylesheet" href="{% static 'facture/css/customp.css' %}">
<div class="w3-panel bg-warning">
  <h2 class="text-center text-white" id='ptitle'>Prévisualisation du BL</h2>
</div>
<hr>
{% localize on %}
<style media="screen">
  #facture {
    color: black !important
  }

  table {
    color: black !important
  }
</style>
<br>
<div class="row justify-content-center" id="facture">
  <div class="col-md-12 col-lg-12 pre-scrollable" style="max-height:55vh">
    <div class="invoice overflow-auto" id="myCanvas">

      <div>
        <header>
          <div class="row">
           
            <div class="col company-details2">
              <h2 class="name">
                TIA MOTO SARLU
              </h2>
              <div>Ny Tsara Indrindra hAtrany</div>
              <div>Siège social: Lot IVX 72B Bis Ankazomanga</div>
              <div>Vente de scooter occasion et accessoires</div>
              <div>Tél: 0330393155</div>
              <div>NIF: 2004105069</div>
              <div>Stat: 46101112020010758</div>
              <div>RCS: 2020 B 00714</div>
            </div>
          </div>
          <div class="text-center" style="position:fixed" >
            <h1><strong> BON DE LIVRAISON </strong> </h1>
          </div>
        </header>
        <main>
          <div class="row contacts">
            <div class="col invoice-to" style="width:70%">
              <div class="text-gray-light">LIVRÉ À:</div>
              <h4 class="to">{{Facture.nom_client_1}}</h4>
              
              <div class="contacts">
                {{Facture.tel_client_1}}
              </div>
            </div>
            <div class="col invoice-details">
              <h4>N°<span id="factnum">{{Facture.num_BL}}</span></h4>
              <div class="date">Date: <span>{{Facture.date_vente}}</span></div>
            </div>
          </div>

          <div class="table-responsive">
            <table class="table" cellspacing="0" cellpadding="0" id='templcontent'
              style="border-right:medium solid black;">
              <thead>
                <tr>
                  <th class="text-center"
                  style="width:10%;
                  border-bottom:1px;
                  border-right:1px;"><b>Ref</b></th>
                  <th class="text-left"
                  style="width:30%;
                  border-bottom:1px;
                  border-right:1px;
                  "><b>DESIGNATION</b></th>
                  <th class="text-center" style="border-bottom:1px;border-right:1px"><b>PU HT</b></th>
                  <th class="text-center" style="border-bottom:1px;border-right:1px"><b>TVA</b></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="w3-large text-center" style="border-right:1px">{{Facture.Ref}}</td>
                  <td class="text-left" style="border-right:1px">
                    <p>
                      {{Facture.nom_moto}}
                    </p>
                    <p>Moteur n°</p>
                    <p><b>{{Facture.num_moteur}}</b></p>
                    <p>{{Facture.volume_moteur}}</p>
                  </td>
                  <td class="qty text-right" id="id_PU_HT" style="border-right:1px">{{Facture.PU_HT}} Ar</td>
                  <td class="total text-right" id="id_TVA" style="border-right:1px">{{Facture.TVA}} Ar</td>
                </tr>
              </tbody>
              <tfoot style="border:none!important">
                <tr>
                  <td colspan="2"></td>
                  <td colspan="1" style="border:1px solid black;border-right:1px;border-top:1px" id="id_PV">PRIX TOTAL TTC</td>
                  <td class="text-right" style="border:1px solid black;border-right:1px;border-top:1px">{{Facture.PV}} Ar</td>
                </tr>
              </tfoot>
            </table>
          </div>
      </div>
      <table class="table table-bordered" style="
                border-width:1px!important;
                border-color:#000!important;
                border-bottom-width:1px!important;
                border-right-width:1px!important;">
        <tr>
          <td style="border-left:1px;border-top:1px;border-bottom:1px">
            {{Facture.montant_lettre}}

          </td>
        </tr>
      </table>
      <br>
      <div class="w3-padding-48"></div>
      <div class="table-responsive">
        <table class="table table-borderless">
          <tr class="text-center" style="border:none!important">
            <td>Vendeur</td>
            <td>Client</td>
          </tr>
        </table>
      </div>
      <div class="w3-padding-48"></div>
      <div class="w3-padding-48"></div>

      </main>
      <footer>
        <p>Les marchandises vendues ne sont ni reprises ni échangées.</p>
        <p>Scooter vendu dans l'état sans aucune garantie.</p>
      </footer>


    </div>

    <!-- double pages -->
    <div class="invoice overflow-auto" id="myCanvasDouble">
      <table style="width: 100%;" >
        <tr>
        <td style="border:0px!important; padding-right:1.25cm!important">
          <div>
            <header>
              <div class="row">
                
                <div class="col company-details2">
                  <h2 class="name">
                    TIA MOTO SARLU
                  </h2>
                  <div>Ny Tsara Indrindra hAtrany</div>
                  <div>Siège social: Lot IVX 72B Bis Ankazomanga</div>
                  <div>Vente de scooter occasion et accessoires</div>
                  <div>Tél: 0330393155</div>
                  <div>NIF: 2004105069</div>
                  <div>Stat: 46101112020010758</div>
                  <div>RCS: 2020 B 00714</div>
                </div>
              </div>
              <div class="text-center">
                <h1 style="font-size:xxxlarge"> <strong> BON DE LIVRAISON </strong></h1>
              </div>
            </header>
            <main>
              <div class="row contacts">
                <div class="col invoice-to" style="width:70%">
                  <div class="text-gray-light">LIVRÉ À:</div>
                  <h4 class="to">{{Facture.nom_client_1}}</h4>
                 
                  <div class="contacts">
                    Tel: {{Facture.tel_client_1}}
                  </div>
                </div>
                <div class="col invoice-details">
                  <h4>N°<span id="factnum">{{Facture.num_BL}}</span></h4>
                  <div class="date">Date: <span>{{Facture.date_vente}}</span></div>
                </div>
              </div>
<div class="row"> 
  <div class="col">
  <p><b style="text-decoration:underline">Modèle:</b>  {{Facture.nom_moto}} </p>
  <p><b style="text-decoration:underline">Numéro moteur:</b>  {{Facture.num_moteur}}</p> 
  <p><b style="text-decoration:underline">Prix:</b>  {{Facture.PV}} Ar</p>   
  </div>
</div> 

          <br><div class="w3-padding-48"></div>
          <div class="table-responsive">
            <table class="table table-borderless">
              <tr class="text-center" style="border:none!important">
                <td>Vendeur</td>
                <td>Client</td>
              </tr>
            </table>
          </div>
          <div class="w3-padding-48"></div>
          <div class="w3-padding-48"></div>
          <div class="w3-padding-48">
          </div>
          </main>
          <footer>
            <h4><strong>TSY AZO ANAOVANA ASSURANCE </strong></h4>
            <p>Les marchandises vendues ne sont ni reprises ni échangées.</p>
            <p>Scooter vendu dans l'état sans aucune garantie.</p>
          </footer>

        </td>
        <td style="border:0px!important; padding-left:1.25cm!important">
          <div>
            <header>
              <div class="row">
                
                <div class="col company-details2">
                  <h2 class="name">
                    TIA MOTO SARLU
                  </h2>
                  <div>Ny Tsara Indrindra hAtrany</div>
                  <div>Siège social: Lot IVX 72B Bis Ankazomanga</div>
                  <div>Vente de scooter occasion et accessoires</div>
                  <div>Tél: 0330393155</div>
                  <div>NIF: 2004105069</div>
                  <div>Stat: 46101112020010758</div>
                  <div>RCS: 2020 B 00714</div>
                </div>
              </div>
              <div class="text-center">
                <h1 style="font-size:xxxlarge"> <strong> BON DE LIVRAISON </strong></h1>
              </div>
            </header>
                       <main>
              <div class="row contacts">
                <div class="col invoice-to" style="width:70%">
                  <div class="text-gray-light">LIVRÉ À:</div>
                  <h4 class="to">{{Facture.nom_client_1}}</h4>
                 
                  <div class="contacts">
                    Tel: {{Facture.tel_client_1}}
                  </div>
                </div>
                <div class="col invoice-details">
                  <h4>N°<span id="factnum">{{Facture.num_BL}}</span></h4>
                  <div class="date">Date: <span>{{Facture.date_vente}}</span></div>
                </div>
              </div>
<div class="row"> 
  <div class="col">
  <p><b style="text-decoration:underline">Modèle:</b>  {{Facture.nom_moto}} </p>
  <p><b style="text-decoration:underline">Numéro moteur:</b>  {{Facture.num_moteur}}</p> 
  <p><b style="text-decoration:underline">Prix:</b>  {{Facture.PV}} Ar</p>   
  </div>
</div> 
          <br>
          <div class="w3-padding-48"></div>
          <div class="table-responsive">
            <table class="table table-borderless">
              <tr class="text-center" style="border:none!important">
                <td>Vendeur</td>
                <td>Client</td>
              </tr>
            </table>
          </div>
          <div class="w3-padding-48"></div>
          <div class="w3-padding-48"></div>
          <div class="w3-padding-48">
          </div>
          </main>
          <footer>
            <h4><strong>TSY AZO ANAOVANA ASSURANCE </strong></h4>
            <p>Les marchandises vendues ne sont ni reprises ni échangées.</p>
            <p>Scooter vendu dans l'état sans aucune garantie.</p>
          </footer>
        </td>
        </tr>
      </table>
    </div>

  </div>
</div>
{% endlocalize %}
<hr class="mb-3">
<div class="row justify-content-center">
  {% block btnRedir %}{% endblock btnRedir %}
</div>

facture/templates/facture/previewBL/previewBLMotoWredir.html
{% extends "facture/previewBL/previewBLMotoTemplate.html" %}
{% load static %}
{% block btnRedir %}
{% include "facture/previewBL/btnRedirPrev.html" %}
{% endblock btnRedir %}