DJ1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.static import serve 
from rest_framework_simplejwt import views as jwt_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('', include('base.urls')),
    path('', include('myapp.urls')),
    path('', include('moto.urls')),
    path('',include('caisseTana.urls')),
    path('',include('caisseTamatave.urls')),
    path('',include('versement.urls')),
    path('',include('importateur.urls')),
    path('',include('exportateur.urls')),
    path('',include('compagnie.urls')),
    path('',include('operation.urls')),
    path('',include('facture.urls')),
    path('accounts/', include('allauth.urls')),
    path('',include('accounts.urls')),
    path('',include('commercial.urls')),
    path('',include('caisseMoto.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    import mimetypes
    mimetypes.add_type("application/javascript",".js",True)

facture/urls.py
from django.urls import path
from facture import views
urlpatterns = [
    path('facture/edit/<int:id>',views.editFacture,name='editFacture'),
    path('facture/preview/<int:id>',views.previewFacture,name='previewFacture'),
    path('facture/initFacture',views.initFacture,name='initFacture'),
    path('facture/editFactureMoto/<int:id>',views.editFactureMoto,name='editFactureMoto'),
    path('facture/editBLMoto/<int:id>',views.editBLMoto,name='editBLMoto'),
    path('facture/previewFactureMoto/<int:id>',views.previewFactureMoto,name='previewFactureMoto'),
    path('facture/previewBLMoto/<int:id>',views.previewBLMoto,name='previewBLMoto'),
    path('facture/total2word/<int:number>',views.total2word,name='total2word'),
]

moto/models.py
from django.db import models

# Create your models here.
class Moto(models.Model):
    ID_Moto = models.IntegerField(blank=True,null=True,unique=True)
    date_entree = models.DateField(auto_now=False,blank=True,null=True)
    nom_moto = models.CharField(max_length=50,blank=True,null=True)
    num_moteur = models.CharField(max_length=50,blank=True,null=True,unique=True)
    FRN = models.CharField(max_length=50,blank=True,null=True)
    PA = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    PV = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    date_vente = models.DateField(auto_now=False,null=True,blank=True)
    nom_client_1 = models.CharField(max_length=50, blank=True,null=True)
    CIN_Num_Client_1 = models.CharField(max_length=50, blank=True,null=True)
    PJ_CIN_Client_1_recto = models.ImageField(blank=True,null=True,upload_to='images')
    PJ_CIN_Client_1_verso = models.ImageField(blank=True,null=True,upload_to='images')
    tel_client_1 = models.CharField(max_length=50, blank=True,null=True)
    adresse_client_1 = models.CharField(max_length=50, blank=True,null=True)
    num_BL = models.IntegerField(null=True,unique=True)
    num_sur_facture = models.IntegerField(null=True,unique=True)
    PJ_Facture = models.FileField(blank=True, null=True, upload_to='images')
    nom_client_2 = models.CharField(max_length=50, blank=True,null=True)
    tel_client_2 = models.CharField(max_length=50, blank=True,null=True)
    adresse_client_2 = models.CharField(max_length=50, blank=True,null=True)
    CIN_Num_Client_2 = models.CharField(max_length=50, blank=True,null=True)
    PJ_CIN_Client_2_recto = models.ImageField(blank=True,null=True,upload_to='images')
    PJ_CIN_Client_2_verso = models.ImageField(blank=True,null=True,upload_to='images')
    montant_reparation = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    motif_reparation = models.CharField(max_length=50,blank=True,null=True)
    commercial = models.CharField(max_length=50,blank=True,null=True)
    volume_moteur = models.CharField(max_length=50,blank=True,null=True)
    PU_HT = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    TVA = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    PT = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    montant_lettre = models.CharField(max_length=50,blank=True)
    Ref = models.IntegerField(blank=True, null=True)
    archive = models.BooleanField(default=False)
    carte_rose = models.CharField(max_length=50,blank=True,null=True)
    carte_grise = models.CharField(max_length=50,blank=True,null=True)
    model_no_1 = models.CharField(max_length=50,blank=True,null=True)
    magasin = models.CharField(max_length=50,blank=True,null=True)
    date_facture = models.DateField(auto_now = False, null = True,blank=True)
    date_BL = models.DateField(auto_now = False, null = True)
    localisation = models.CharField(max_length=50,blank=True,null=True)
    date_arrivee = models.DateField(auto_now = False, null = True)
    fournisseur = models.CharField(max_length=50,blank=True,null=True)
    
    def __str__(self):
        return self.nom_moto

facture/forms.py
from django import forms
from django.forms import ModelForm
from operation.models import Operation
from django.core.exceptions import ValidationError
from decimal import Decimal, DecimalException
from django.utils import formats
from django.utils.encoding import force_text
from moto.models import Moto
from .models import FactureMoto

class Thousands(forms.DecimalField):
    def to_python(self, value):
        if value in self.empty_values:
            return None
        if self.localize:
            value = formats.sanitize_separators(value)
        value = force_text(value).strip().replace(' ', '')

        try:
            value = Decimal(value)
        except DecimalException:
            raise ValidationError(
                self.error_messages['invalid'], code='invalid')
        return value

class factureForm(ModelForm):
    Facture_Date_Facture = forms.DateField(widget=forms.DateInput(attrs={'type':'date','class':'form-control w3-margin-bottom','max': 'today'}),required=False)

    Facture_OT_Honoraire = Thousands(label='OT - Honoraire',max_digits=20, decimal_places=2, widget=forms.TextInput())

    Facture_Autres_Montant = Thousands(label='Autres montant',max_digits=20, decimal_places=2, widget=forms.TextInput())

    Facture_BAD_Montant = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Overstay_Montant = Thousands(label='Overstay',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Surestaries_Montant = Thousands(label='Surestaries',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Debarquement = Thousands(label='Debarquement',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Magasinage_Montant = Thousands(label='Magasinage',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Droit_Compromis = Thousands(label='Droit compromis',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Amende_Montant = Thousands(label='Amende',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_OV_Montant = Thousands(label='OV',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_OV_Docker = Thousands(label='Docker',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Montant_Fret = Thousands(label='Fret',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Immobilisation = Thousands(label='Immobilisation',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_SousTotal = Thousands(max_digits=20,decimal_places=2, widget=forms.TextInput())

    TotalFacture = Thousands(max_digits=20,decimal_places=2, widget=forms.TextInput())
    Tax = Thousands(max_digits=20,decimal_places=2, widget=forms.TextInput())


    def __init__(self, *args, **kwargs):
        super(factureForm, self).__init__(*args, **kwargs)

        for name in self.fields.keys():
            if name != 'Facture_Date_Facture':
                self.fields[name].widget.attrs.update({'class': 'form-control'})
                self.fields[name].required = False

    class Meta:
        model = Operation
        fields = [
            'Facture_OT_Honoraire','Facture_Autres_Montant','Facture_BAD_Montant','Facture_Overstay_Montant','Facture_Surestaries_Montant','Facture_Debarquement','Facture_Magasinage_Montant','Facture_Droit_Compromis','Facture_Amende_Montant','Facture_OV_Montant','Facture_OV_Docker','Facture_Montant_Fret','Facture_Immobilisation','Facture_Num_Facture','Facture_Nom_Client','Facture_Adresse_Client','Facture_Contact_Client','Facture_email_client','Facture_Date_Facture','Facture_SousTotal','Tax','TotalFacture'
        ]


class factureMotoForm(ModelForm):
    """docstring for factureMoto."""
    PU_HT = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    TVA = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    PV = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    date_vente = forms.DateField(widget=forms.DateInput(attrs={'type':'date','class':'form-control w3-margin-bottom','max': 'today'}),required=False)
    num_sur_facture = forms.CharField(label="Num facture",widget=forms.TextInput())
    def __init__(self, *args, **kwargs):
        super(factureMotoForm, self).__init__(*args, **kwargs)

        for name in self.fields.keys():
            if name != 'Facture_Date_Facture':
                self.fields[name].widget.attrs.update({'class': 'form-control'})
                self.fields[name].required = False

    class Meta:
        model = Moto
        fields = [
        'nom_client_2','CIN_Num_Client_2','adresse_client_2','tel_client_2','volume_moteur','PU_HT','TVA','PT','montant_lettre','PV','date_vente','Ref','num_sur_facture'
        ]

class BLMotoForm(ModelForm):
    """docstring for factureMoto."""
    PV = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    date_vente = forms.DateField(widget=forms.DateInput(attrs={'type':'date','class':'form-control w3-margin-bottom','max': 'today'}),required=False)
    num_BL= forms.CharField(label="Num BL",widget=forms.TextInput())

    def __init__(self, *args, **kwargs):
        super(BLMotoForm, self).__init__(*args, **kwargs)

        for name in self.fields.keys():
            if name != 'Facture_Date_Facture':
                self.fields[name].widget.attrs.update({'class': 'form-control'})
                self.fields[name].required = False

    class Meta:
        model = Moto
        fields = [
        'nom_client_1','tel_client_1','PU_HT','TVA','PT','PV','date_vente','Ref','num_BL'
        ]

facture/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib import messages

from operation.models import Operation
from .forms import factureForm, factureMotoForm, BLMotoForm
from operation.receptionForm import ReceptionForm
from moto.models import Moto
from facture.models import FactureMoto, BLMoto

from num2words import num2words


# Create your views here.

def editFacture(request, id=None, pk=None):
    operation = get_object_or_404(Operation, pk=id)
    if request.method == 'POST':
        form = factureForm(request.POST, instance=operation)
        if form.is_valid():
            form.save()
            messages.success(request, "success")
        else:
            messages.error(request, "error")
    else:
        form = factureForm(instance=operation)
        recform = ReceptionForm(instance=operation)
        messages.success(request, "success")
    context = {
        'form': form,
        'id': operation.id,
        'pk': id
    }
    return render(request, 'facture/edit.html', context)


def previewFacture(request, id=None):
    Facture = get_object_or_404(Operation, pk=id)
    return render(request, 'facture/preview.html',
                  {'Facture': Facture, 'id': Facture.id, 'client': Facture.Facture_Nom_Client})


def initFacture(request):
    if request.is_ajax and request.method == 'GET':
        id = request.GET.get("id", None)
        print("id = ", id)
        curOp = Operation.objects.get(pk=id)
        Facture_OT_Honoraire = curOp.OT_Honoraire
        print("Facture_OT_Honoraire = ", Facture_OT_Honoraire)
        Facture_Autres_Montant = curOp.Autres_Montant
        Facture_BAD_Montant = curOp.BAD_Montant
        Facture_Overstay_Montant = curOp.Overstay_Montant
        Facture_Surestaries_Montant = curOp.Surestaries_Montant
        Facture_Debarquement = curOp.Montant_MICTSL
        Facture_Magasinage_Montant = curOp.Magasinage_Montant
        Facture_Droit_Compromis = curOp.Droit_Compromis
        Facture_Amende_Montant = curOp.Amende_Montant
        Facture_OV_Montant = curOp.OV_Montant
        Facture_OV_Docker = curOp.OV_Docker
        Facture_Montant_Fret = curOp.Montant_Fret
        Facture_Immobilisation = curOp.Immobilisation
        Facture_Nom_Client = curOp.Client

        return JsonResponse(
            {'Facture_OT_Honoraire': Facture_OT_Honoraire, 'Facture_Autres_Montant': Facture_Autres_Montant,
             'Facture_BAD_Montant': Facture_BAD_Montant, 'Facture_Overstay_Montant': Facture_Overstay_Montant,
             'Facture_Surestaries_Montant': Facture_Surestaries_Montant, 'Facture_Debarquement': Facture_Debarquement,
             'Facture_Magasinage_Montant': Facture_Magasinage_Montant,
             'Facture_Droit_Compromis': Facture_Droit_Compromis, 'Facture_Amende_Montant': Facture_Amende_Montant,
             'Facture_OV_Montant': Facture_OV_Montant, 'Facture_OV_Docker': Facture_OV_Docker,
             'Facture_Montant_Fret': Facture_Montant_Fret, 'Facture_Immobilisation': Facture_Immobilisation,
             'Facture_Nom_Client': Facture_Nom_Client}, status=200)


def editFactureMoto(request, id=None):
    moto = get_object_or_404(Moto, pk=id)
    pageTitle = "Moto n°" + str(id)

    if request.method == 'POST':
        form = factureMotoForm(request.POST, instance=moto)
        if form.is_valid():
            form.save()
            messages.success(request, "success")
        else:
            messages.error(request, 'error')
    else:
        form = factureMotoForm(instance=moto)
    context = {'form': form,
               'moto': moto,
               'pageTitle': pageTitle,
               'pk': id
               }
    return render(request, 'facture/editFacture/editFactureMoto.html', context)


def editBLMoto(request, id=None):
    moto = get_object_or_404(Moto, pk=id)
    numBLlast = BLMoto.objects.last()
    pageTitle = "Moto n°" + str(id)
    if request.method == 'POST':
        form = BLMotoForm(request.POST, instance=moto)
        if form.is_valid():
            form.save()
            messages.success(request, 'success')
        else:
            messages.error(request, 'error')
    else:
        form = BLMotoForm(instance=moto)
    context = {'form': form,
               'moto': moto,
               'pageTitle': pageTitle,
               'pk': id
               }
    return render(request, 'facture/editBL/editBLMoto.html', context)


def previewFactureMoto(request, id=None):
    Facture = get_object_or_404(Moto, pk=id)
    pageTitle = "Moto n°" + str(Facture.ID_Moto)
    context = {
        'Facture': Facture, 
        'pageTitle': pageTitle,
        'pk': id
    }
    return render(request, 'facture/previewFacture/previewFactureMoto.html',context)


def previewBLMoto(request, id=None):
    Facture = get_object_or_404(Moto, pk=id)
    pageTitle = "Moto n°" + str(Facture.ID_Moto)
    context = {
        'Facture': Facture, 
        'pageTitle': pageTitle,
        'pk': id
    }
    return render(request, 'facture/previewBL/previewBLMoto.html', context)

def total2word(request,number):
    word = num2words(number,lang='fr')
    word = word.replace("-"," ")
    return JsonResponse({'Total':word},safe=False)

facture/templates/facture/editBL/btnEditBL.html
{% block btnRedir %}
<div class="">
  <a href="{% url 'index' %}" class="btn btn-secondary"><i class="fas fa-chevron-left fa-fw"></i>Retour</a>
  <button type="submit" name="button" class="btn btn-primary" form="formBL"><i class="fas fa-save fa-fw"></i> Enregistrer</button>
  <a href="{% url 'previewBLMoto' id=moto.id %}" class="btn btn-warning disabled" id='preview'><i class="fas fa-magic fa-fw"></i>Preview</a>
</div>
{% endblock btnRedir %}

facture/templates/facture/editBL/editBLMoto.html
{% extends 'base/blankbone.html'%}
{% block sidebar %}
{% include 'base/sidebar.html' %}
{% endblock sidebar %}
{% block topbar %}
{% include "base/topbar2.html" %}
{% endblock topbar %}
{% load static %}
{% block content %}
{% load humanize %}
{% load l10n %}
{% include "facture/editBL/editBLMotoWredir.html" %}
{% endblock content %}
{% block js %}
{% include "base/modal.html" %}
<script src="{% static 'facture/js/jszip.min.js' %}" charset="utf-8"></script>
<script src="{% static 'facture/js/kendo.all.min.js' %}" charset="utf-8"></script>
<script src="{% static 'facture/js/script.js' %}" charset="utf-8"></script>
<script src="{% static 'facture/js/calcul.js' %}" charset="utf-8"></script>
<script src="{% static 'base/js/cleave.min.js' %}" charset="utf-8"></script>
<script type="text/javascript">
  // KajyMoto
  var PT = parseFloat($("#id_PV").val().replace(/ /g, ''));
  // console.log("PT test = " + PT);
  if (!$("#id_PV").val()) {
    PT = 0;
  }
fetch(`/facture/total2word/${PT}`).then((data)=> data.json()).then((res)=> $('input[name="montant_lettre"]').attr('value', `${res.Total.toUpperCase()} ARIARY`))

  var PUHT = PT / 1.2;
  var TVA = 0.2 * PUHT;
  document.getElementById('id_PU_HT').value = PUHT;
  document.getElementById('id_TVA').value = TVA;
  this.id_PV = new Cleave('#id_PV', {
    numeral: true,
    numeralDecimalMark: '.',
    delimiter: ' '
  });
  this.id_PU_HT = new Cleave('#id_PU_HT', {
    numeral: true,
    numeralDecimalMark: '.',
    delimiter: ' '
  });
  this.id_TVA = new Cleave('#id_TVA', {
    numeral: true,
    numeralDecimalMark: '.',
    delimiter: ' '
  });
  $(document).change(function () {
    let PT = parseFloat($("#id_PV").val().replace(/ /g, ''));
    console.log("PT test = " + PT);
    if (!$("#id_PV").val()) {
      PT = 0;
    }

    this.id_PV = new Cleave('#id_PV', {
      numeral: true,
      numeralDecimalMark: '.',
      delimiter: ' '
    });
    console.log("test being");
  })
</script>
<script type="text/javascript">
  $(document).ready(function () {
    $('#pageTitle').addClass('fas fa-motorcycle fa-fw w3-margin-right');
  })
</script>
<script>
{% if messages %}
  {% for message in messages %}
  var message = "{{message}}"
  if (message === "success") {
      $('#preview').removeClass("disabled")
    }
  {% endfor %}
{% endif %}
  $('#id_volume_moteur').attr('required', 'true');
  $('#id_nom_client_1').attr('required', 'true');
  $('#id_CIN_Num_Client_1').attr('required', 'true');
  $('#id_tel_client_1').attr('required', 'true');
  $('#id_num_sur_facture').attr('required', 'true');
  $('#id_date_vente').attr('required', 'true');
  $('#id_num_BL').attr('required', 'true');
  $('#motoMenu').addClass("active");

          $("#linkEdition").click(() => {
            let ids = {{pk}}
                console.log(ids)
            let url = "{% url 'editMoto' pk=123 %}"
            document.location.href = url.replace('123', ids)
        })
        $("#linkFacture").click(() => {
            let ids = {{pk}}
                console.log(ids)
            let url = "{% url 'editFactureMoto' id=123 %}"
            document.location.href = url.replace('123', ids)
        })
</script>
{% endblock js %}

facture/templates/facture/editBL/editBLMotoTemplate.html
{% load l10n %}
{% load static %}
<link rel="stylesheet" href="{% static 'facture/css/kendo.common-material.min.css' %}">
<link rel="stylesheet" href="{% static 'facture/css/kendo.material.min.css' %}">
<link rel="stylesheet" href="{% static 'facture/css/facture.css' %}">
<style media="screen">
  #facture {
    color: black !important
  }

  table {
    color: black !important
  }

  .form-control {
    color: black !important
  }
  label{
    color:black!important
  }
</style>
<div class="row justify-content-center align-bottom">
  <div class="col-md-10 col-lg-10">
    <ul class="nav nav-tabs w3-border-0">
      <li class="w3-margin-right" style="cursor: pointer;" id="linkEdition">
        <h4 class="w3-bottombar w3-border-light-grey text-gray-500 w3-hover-border-green w3-hover-text-green">Edition</h4>
      </li>
      <li class="w3-margin-right" style="cursor: pointer;" id="linkFacture">
        <h4 class="w3-bottombar w3-border-light-grey text-gray-500 w3-hover-text-cyan w3-hover-border-cyan">Facture</h4>
      </li>
      <li class="w3-margin-right" id="linkBL">
        <h4 class="w3-bottombar w3-text-amber w3-border-amber">BL</h4>
      </li>
    </ul>
  </div>
</div>
<form class="form-group" method="post" id="formBL">
  {% csrf_token %}
  {% localize off %}
  <div class="row justify-content-center">
    <div class="col-md-10 col-lg-10 pre-scrollable" style="max-height:55vh">
      <div class="invoice overflow-auto" id="myCanvas">
        <div style="min-width: 600px">
          <header>
            <div class="row">
             
              <div class="col company-details2">
                <h2 class="name">
                  <a target="_blank" href="">
                    TIA MOTO SARLU
                  </a>
                </h2>
                <div>Ny Tsara Indrindra hAtrany</div>
                <div>Siège social: Lot IVX 72B Bis Ankazomanga</div>
                <div>Vente de scooter occasion et accessoires</div>
                <div>Tél: 0330393155</div>
                <div>NIF: 2004105069</div>
                <div>Stat: 46101112020010758</div>
                <div>RCS: 2020 B 00714</div>
              </div>
            </div>
            <div class="text-center h1">
              <h1 >BON DE LIVRAISON</h1>
            </div>
          </header>
          <main>

            <div class="row justify-content-center">

            </div>
            <div class="row contacts">
              <div class="col invoice-to">
                <div class="text-gray-light">Livré à:</div>
                <div>Nom du client</div>
                <h2 class="to">{{form.nom_client_1}}
                </h2>
               
                <div class="text-gray-800">Contact(s) du client</div>
                <div class="email">{{form.tel_client_1}}</div>
              </div>
              <div class="col invoice-details w3-right">
                <h4>N°{{form.num_BL}}</h4>
                {% load l10n %}
                <div class="date">Date: <span>{{form.date_vente}}</span></div>
              </div>
            </div>
            <div class="table-responsive">
              <table class="table" cellspacing="0" cellpadding="0">
                <thead>
                  <tr>
                    <th class="text-center" style="width:10%"><b>Ref</b></th>
                    <th class="text-left" style="width:50%"><b>DESIGNATION</b></th>
                    <th class="text-center"><b></b></th>
                    <th class="text-center"><b></b></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="w3-large text-center">{{form.Ref}}</td>
                    <td class="text-left">
                      <p>
                        {{moto.nom_moto}}
                      </p>
                      <p>{{moto.num_moteur}}</p>
                      
                    </td>
                  </tr>
                </tbody>
                <tfoot>
                  <tr>
                    <td colspan="2"></td>
                    <td colspan="1">PRIX DE VENTE</td>
                    <td>{{form.PV}} Ar</td>
                  </tr>
                </tfoot>
              </table>
            </div><br>
           
            <div class="table-responsive">
              <table class="table table-borderless">
                <tr class="text-center">
                  <td>Vendeur</td>
                  <td>Client</td>
                </tr>
              </table>
            </div>
          </main>
          <footer>
            <h4><strong>TSY AZO ANAOVANA ASSURANCE</strong></h4>
            <p>Les marchandises vendues ne sont ni reprises ni échangées.</p>
            <p>Scooter vendu dans l'état sans aucune garantie.</p>
          </footer>
        </div>
      </div>
    </div>
    <br>

  </div>
  {% endlocalize %}
</form>
    <br class="mb-3">
    <div class="row justify-content-center w3-margin">
      {% block btnRedir %}{% endblock btnRedir %}
    </div>

facture/templates/facture/editBL/editBLMotoWredir.html
{% extends "facture/editBL/editBLMotoTemplate.html" %}
{% block btnRedir %}
{% include "facture/editBL/btnEditBL.html" %}
{% endblock btnRedir %}