DJ1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.static import serve 
from rest_framework_simplejwt import views as jwt_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('', include('base.urls')),
    path('', include('myapp.urls')),
    path('', include('moto.urls')),
    path('',include('caisseTana.urls')),
    path('',include('caisseTamatave.urls')),
    path('',include('versement.urls')),
    path('',include('importateur.urls')),
    path('',include('exportateur.urls')),
    path('',include('compagnie.urls')),
    path('',include('operation.urls')),
    path('',include('facture.urls')),
    path('accounts/', include('allauth.urls')),
    path('',include('accounts.urls')),
    path('',include('commercial.urls')),
    path('',include('caisseMoto.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    import mimetypes
    mimetypes.add_type("application/javascript",".js",True)

caisseTamatave/urls.py
from django.urls import path
from caisseTamatave import views

urlpatterns = [
    path('caisseTamatave/',views.indexTamatave,name='indexTamatave'),
    path('caisseTamatave/refSolde/<int:pk>',views.refSoldeTamatave,name='refSoldeTamatave'),
    path('caisseTamatave/create',views.createCaisseTamatave,name='createCaisseTamatave'),
    path('caisseTamatave/edit/<int:pk>',views.editCaisseTamatave,name='editCaisseTamatave'),
    path('caisseTamatave/delete/<int:pk>',views.deleteCaisseTamatave,name='deleteCaisseTamatave'),

]

caisseTamatave/models.py
from django.db import models

# Create your models here.


class Caisse(models.Model):
    libellee = models.CharField(max_length=50)
    date = models.DateField(auto_now=False, null=True)
    depense = models.DecimalField(null=True,default="0",decimal_places=2,max_digits=20)
    recette = models.DecimalField(null=True,default="0",decimal_places=2,max_digits=20)
    PJ = models.FileField(blank=True, upload_to='images')

    def __str__(self):
        return self.libellee

class Solde(models.Model):
    soldeInitial = models.DecimalField(null=True,default="0",decimal_places=2,max_digits=20)
    soldeActuel = models.DecimalField(null=True,default="0",decimal_places=2,max_digits=20)

caisseTamatave/views.py
from django.shortcuts import render, get_object_or_404, redirect
from base.views import topbar
from .form import CaisseForm
from .models import Caisse, Solde
from .soldeForm import SoldeForm
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect
from django.contrib import messages

# Create your views here.
pageTitle = "Caisse Transit"
def indexTamatave(request):
    caisseTamataves = Caisse.objects.all()
    solde = Solde.objects.all()
    
    return render(request,'caisseTamatave/index.html',{'caisseTamataves':caisseTamataves,'solde':solde,'pageTitle':pageTitle})

def refSoldeTamatave(request,pk=None):
    
    solde = get_object_or_404(Solde, pk=pk)
    if request.method == 'POST':
        form = SoldeForm(request.POST,instance=solde)

        CaisseTamatave = Caisse.objects.all()
        if form.is_valid():
            form.save()
            soldeNow = solde.soldeInitial
            for caisse in CaisseTamatave:
                soldeNow = soldeNow + caisse.recette - caisse.depense

            solde.soldeActuel = soldeNow
            solde.save()
            messages.success(request,'success')
            return HttpResponseRedirect('/caisseTamatave/')
        else:
            messages.error(request,'error')
    else:
        form = SoldeForm(instance=solde)
    return render(request,'caisseTamatave/refSolde.html',{'form': form,'pageTitle':pageTitle})

def createCaisseTamatave(request):
    
    subtitle = "Nouvelle enregistrement"
    if request.method == 'POST':
        form = CaisseForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request,'create')
            lastCaisseTamatave = Caisse.objects.last()
            i = Solde.objects.latest('id')
            refSoldeTamatave(request,pk=i.pk)
            return redirect('editCaisseTamatave', pk=lastCaisseTamatave.pk)
        return HttpResponseRedirect('/caisseTamatave/')
    else:
        form = CaisseForm()
    return render(request,'caisseTamatave/edit.html',{'form':form,'pageTitle':pageTitle,'subtitle':subtitle})

def editCaisseTamatave(request,pk=None):
    
    subtitle = "Edition"
    caisse = get_object_or_404(Caisse, pk=pk)
    if request.method == 'POST':
        form = CaisseForm(request.POST,request.FILES,instance=caisse)

        if form.is_valid():
            form.save()
            messages.success(request,'success')
            i = Solde.objects.latest('id')
            refSoldeTamatave(request,pk=i.pk)
        return HttpResponseRedirect('/caisseTamatave/')

    else:
        form = CaisseForm(instance=caisse)
    return render(request,'caisseTamatave/edit.html',{'form': form,'pageTitle':pageTitle,'subtitle':subtitle})

def deleteCaisseTamatave(request,pk=None):
    
    caisse = get_object_or_404(Caisse, pk=pk)
    if request.method == 'POST':
        caisse.delete()
        messages.success(request,'delete')
        return HttpResponseRedirect('/caisseTamatave/')

    return render(request,'caisseTamatave/delete.html',{'caisse':caisse,'pageTitle':pageTitle})

caisseTamatave/templates/caisseTamatave/delete.html
{% extends 'base/main.html'%}


{% block content %}
    <div class="jumbotron w3-pale-red">
        <div class="container justify-content-center">
            <h3 class="w3-xxlarge">Confirmation de suppression</h3>
            <hr class="w3-border-grey">
            <div class="row">

                <div class="lead col w3-text-red"><h4>Ete-vous sure de supprimer {{ caisse.libellee }} ?</h4></div>
            </div>
<br>
            <div class="row justify-content-center">
              <form action="{% url 'deleteCaisseTamatave' caisse.id %}" method="post" class="justify-content-center">
                  {% csrf_token %}
                  <input type="submit" value="Supprimer" class="btn btn-danger w3-margin-left">

                  <a href="/caisseTana/" class="btn btn-info w3-margin-left">Annuler</a>
              </form>
            </div>
        </div>



    </div>
    <br><br>
{% endblock content %}

caisseTamatave/templates/caisseTamatave/edit.html
{% extends 'base/blankbone.html'%} {% if request.user.is_staff %} {% block
sidebar %} {% include "base/sidebar.html" %} {% endblock sidebar %} {% endif %}
{% block topbar %} {% include "base/topbar.html" %} {% endblock topbar %} {%
load static %} {% block content %} {% load humanize %}
<h1 class="h3 mb-4 text-danger text-center">{{subtitle}}</h1>
<hr class="w3-border-red" />
<form
	id="myForm"
	method="post"
	enctype="multipart/form-data"
	class="text-gray-800"
>
	{% csrf_token %}
	<div class="row justify-content-center">
		<div class="col-md-8 col-lg-4" style="max-height: 60vh">{{ form }}</div>
		<hr class="mb-3" />
	</div>
</form>
<div class="row justify-content-center">
	<div class="w3-margin">
		<br />
		<a href="/caisseTamatave/" class="btn btn-primary"
			><i class="fas fa-arrow-alt-circle-left w3-large w3-margin-right"></i
			>Retour</a
		>
		<button class="btn btn-success" type="submit" form="myForm">
			<i class="fas fa-save w3-large w3-margin-right"></i> Enregistrer
		</button>
		<a href="{% url 'createCaisseTamatave' %}" class="btn btn-danger"
			><i class="fas fa-plus-circle fa-fw"></i> Nouvelle enregistrement</a
		>
	</div>
</div>
{% endblock %} {% block js %} {% include "base/modal.html" %}
<script src="{% static 'base/js/cleave.min.js' %}" charset="utf-8"></script>
<script>
	var today = new Date();
	var dd = today.getDate();
	var mm = today.getMonth() + 1; //January is 0!
	var yyyy = today.getFullYear();
	if (dd < 10) {
		dd = "0" + dd;
	}
	if (mm < 10) {
		mm = "0" + mm;
	}

	today = yyyy + "-" + mm + "-" + dd;
	document.getElementById("date").setAttribute("max", today);

	new Cleave("#id_depense", {
		numeral: true,
		numeralDecimalMark: ".",
		delimiter: " ",
	});
	new Cleave("#id_recette", {
		numeral: true,
		numeralDecimalMark: ".",
		delimiter: " ",
	});
</script>
<script>
	$(document).ready(function () {
		$("#accordionSidebar").toggleClass(
			"bg-gradient-primary bg-gradient-danger"
		);
		$("#caisseTamataveMenu").addClass("active");
		$("#pageTitle").addClass("fas fa-cash-register fa-fw w3-margin-right");
		$("h3").addClass("text-danger");
	});
	$("#id_depense").mouseleave(() => {
		console.log($("#id_depense").val());
		if ($("#id_depense").val() === "" || $("#id_depense").val() === " ") {
			document.querySelector("#id_depense").value = 0;
		}
	});
	$("#id_recette").mouseleave(() => {
		console.log($("#id_recette").val());
		if ($("#id_recette").val() === "" || $("#id_recette").val() === " ") {
			document.querySelector("#id_recette").value = 0;
		}
	});
</script>
{% endblock js %}

caisseTamatave/templates/caisseTamatave/index.html
{% extends 'base/blankbone.html'%}
{% if request.user.is_staff %}
{% block sidebar %}
{% include "base/sidebar.html" %}
{% endblock sidebar %}
{% endif %}
{% block topbar %}
{% include "base/topbar.html" %}
{% endblock topbar %}
{% block content %}
{% load static %}
{% load l10n %}
{% localize on %}
<link rel="stylesheet" href="{% static 'base/css/bootstrap-table.min.css'%}">
<link rel="stylesheet" href="{% static 'base/css/bootstrap-table-fixed-columns.min.css'%}">

<div class="card shadow mb-4">
  <div class="card-header mb-4">
    <h6 class="m-0 font-weight-bold w3-text-red">Solde</h6>
  </div>
  <div class="card-body">


    <div class="row justify-content-lg-start text-gray-800">
      <div class="col-md-6 col-lg-2">

        {% for solde in solde %}
       <table class="w3-table w3-bordered text-nowrap text-gray-800">
          <thead>
            <tr>
              <th>Solde initial [Ar]</th>
              <th></th>

            </tr>
          </thead>
          <tbody>
            <tr>
              <td><a href="{% url 'refSoldeTamatave' pk=solde.pk %}" class="btn btn-success"><i class="fas fa-edit w3-margin-right"></i>Modifier</a></td>
              <td class="w3-right-align w3-large">{{solde.soldeInitial}}</td>
            </tr>
          </tbody>

          </tbody>
          <tfooter>
            <tr>
              <th>Solde actuel [Ar]</th>
              <th></th>
            </tr>
          </tfooter>
          <tbody>
            <tr>
              <td></td>
              <td class="w3-right-align w3-large">{{solde.soldeActuel}}</td>
            </tr>
          </tbody>
        </table>
        
        {% endfor %}
      </div>
      <hr class="mb-3">

    </div>




  </div>
</div>
<br>
<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold w3-text-red">Table de récapitulation</h6>
  </div>
  <div class="card-body">
    <div id="toolbar">
      <button class="btn btn-danger" onclick="window.location.href='/caisseTamatave/create'"><i class="fas fa-plus-circle w3-margin-right"></i>Nouvelle enregistrement</button>

    </div>
    <div class="table-responsive text-nowrap">
      <table class="table-striped table-hasthead text-nowrap" id="tableTest1" data-search="true" data-fixed-columns="true" data-fixed-number="1" data-fixed-right-number="1" data-toggle="table" data-show-columns="true" data-pagination="true"
        data-sortable="true" data-show-export="true" data-show-button-icons="true" data-show-pagination-switch="true" data-toolbar="#toolbar">
        <thead class="bg-danger text-white">
          <tr>
            <th data-sortable="true">Libellee</th>
            <th data-sortable="true">Date</th>
            <th data-sortable="true">Depense</th>
            <th data-sortable="true">Recette</th>
            <th>Option</th>
          </tr>
        </thead>

        <tbody>
          {% for i in caisseTamataves %}
          <tr>
            <td>{{i.libellee}}</td>
            <td>{{i.date}}</td>
            <td class="text-right">{{i.depense}}</td>
            <td class="text-right">{{i.recette}}</td>
            <td>
              <a href="{% url 'editCaisseTamatave' pk=i.pk %}" class="btn btn-success"><i class="fas fa-edit w3-margin-right"></i>Editer</a>

              <a href="{% url 'deleteCaisseTamatave' pk=i.pk %}" class="btn btn-danger"><i class="fas fa-trash w3-margin-right"></i>Supprimer</a>
            </td>
          </tr>

          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endlocalize %}
{% endblock content %}
{% block js %}
<!-- Core plugin JavaScript-->
<script src="{% static 'base/js/popper.min.js'%}"></script>
<script src="{% static 'base/js/bootstrap-table.min.js'%}"></script>

<!-- Custom script for this page -->
<script src="{% static 'base/js/bootstrap-table-fixed-columns.min.js' %}"></script>
<script src="{% static 'base/js/bootstrap-table-export.min.js' %}"></script>
<script src="{% static 'base/js/tableExport.min.js' %}"></script>
<script src="{% static 'base/js/jspdf.min.js'%}"></script>
<script src="{% static 'base/js/jspdf.plugin.autotable.js' %}"></script>
<script src="{% static 'base/js/bootstrap-table-mobile.min.js' %}"></script>
<!-- <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/sticky-header/bootstrap-table-sticky-header.min.js"></script> -->
{% include "base/modal.html" %}
<script type="text/javascript">
  $(function() {
    $('#tableTest1').bootstrapTable({
      height: $(window).height(),
      onAll: function(name, args) {
        fixleftwidth()
      }
    });

    function fixleftwidth() {
      setTimeout(function() {
        var fixColumnTds = $(".fixed-table-body-columns tr:first-child td");
        var fixNum = fixColumnTds.length;
        var tableBody = $(".fixed-table-body tbody tr:first-child td");
        for (var i = 0; i < fixNum; i++) {
          fixColumnTds.eq(i).width(tableBody.eq(i).width())
        }
      }, 0)
    }
    fixleftwidth()
    $(window).resize(function() {
      $('#tableTest1').bootstrapTable('resetView');
      fixleftwidth()
    });
  });
</script>
<script>
  $(document).ready(function () {
    $("#accordionSidebar").toggleClass("bg-gradient-primary bg-gradient-danger");
    $("#caisseTamataveMenu").addClass("active");
    $("#pageTitle").addClass("fas fa-cash-register fa-fw w3-margin-right");
    $("h3").addClass("text-danger");
  })
</script>
{% endblock js %}

caisseTamatave/templates/caisseTamatave/refSolde.html
{% extends 'base/blankbone.html'%}
{% if request.user.is_staff %}
{% block sidebar %}
{% include "base/sidebar.html" %}
{% endblock sidebar %}
{% endif %}
{% block topbar %}
{% include "base/topbar.html" %}
{% endblock topbar %}
{% load static %}
{% block content %}
{% load humanize %}
<h1 class="h3 mb-4 text-gray-800 text-center">Editer le solde</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row justify-content-center">
    <div class="col-md-8">
      {{ form }}
    </div>
    <hr class="mb-3">
  </div>
  <div class="row justify-content-center">
    <div class=""><br>
      <a href="/caisseTamatave/" class="btn btn-primary"><i class="fas fa-arrow-alt-circle-left w3-large w3-margin-right"></i>Retour</a>
      <button class=" btn btn-success" type="submit"><i class="fas fa-save w3-large w3-margin-right"></i> Enregistrer</button>

    </div>
  </div>
</form>
{% endblock  %}
{% block js %}
<script src="{% static 'base/js/cleave.min.js' %}" charset="utf-8"></script>

<script type="text/javascript">
  new Cleave('#id_soldeInitial', {
    numeral: true,
    numeralDecimalMark: '.',
    delimiter: ' '
  });
  new Cleave('#id_soldeActuel', {
    numeral: true,
    numeralDecimalMark: '.',
    delimiter: ' '
  });
</script>
<script>
  $(document).ready(function () {
    $("#accordionSidebar").toggleClass("bg-gradient-primary bg-gradient-danger");
    $("#caisseTamataveMenu").addClass("active");
    $("#pageTitle").addClass("fas fa-cash-register fa-fw w3-margin-right");
    $("h3").addClass("text-danger");
  })
</script>
{% endblock js %}